feat: test command as input and upgrade node version used

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -8,6 +8,10 @@ inputs:
   TESTS_SRC_DIR:
     description: "Directory where the tests src is"
     required: true
+  TESTS_COMMAND:
+    description: 'command to run tests. For example npm run test-ci'
+    required: false
+    default: 'npm test'
   RELEASE_CODENAME:
     description: 'Codename for release'
     required: false
@@ -31,9 +35,9 @@ runs:
   steps:
 
     - name: Setup Node.js environment
-      uses: actions/setup-node@v2.1.5
+      uses: actions/setup-node@v2
       with:
-        node-version: "12"
+        node-version: "14"
 
     - name: Setting up cache
       uses: actions/cache@v2
@@ -51,7 +55,7 @@ runs:
     - name: Run tests
       id: acceptance-tests
       working-directory: ${{ inputs.TESTS_SRC_DIR }}
-      run: echo "TESTS_STATUS=good" >> $GITHUB_ENV && export NODE_ENV=${{ inputs.ENVIRONMENT_NAME }} && npm test || echo "TESTS_STATUS=failure" >> $GITHUB_ENV
+      run: echo "TESTS_STATUS=good" >> $GITHUB_ENV && export NODE_ENV=${{ inputs.ENVIRONMENT_NAME }} && ${{ inputs.TESTS_COMMAND }} || echo "TESTS_STATUS=failure" >> $GITHUB_ENV
       shell: bash
       #continue-on-error: true
 
