fix: set correct color when all tests pass

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -25,7 +25,7 @@ inputs:
     description: "Slack's webhook"
     required: true
     
-#TODO: since if and continue-on-error are not supported on composite actions, lines using them are commented
+#TODO: since continue-on-error is not supported on composite actions, lines using it are commented
 runs:
   using: "composite"
   steps:
@@ -51,13 +51,14 @@ runs:
     - name: Run tests
       id: acceptance-tests
       working-directory: ${{ inputs.TESTS_SRC_DIR }}
-      run: export NODE_ENV=${{ inputs.ENVIRONMENT_NAME }} && npm test || if [ $? -eq 0 ]; then echo "TESTS_STATUS=success" >> $GITHUB_ENV; else echo "TESTS_STATUS=failure" >> $GITHUB_ENV; fi
+      run: export NODE_ENV=${{ inputs.ENVIRONMENT_NAME }} && npm test || if [ $? -eq 0 ]; then echo "TESTS_STATUS=good" >> $GITHUB_ENV; else echo "TESTS_STATUS=failure" >> $GITHUB_ENV; fi
       shell: bash
+      #continue-on-error: true
 
     - name: Deploy to Netlify
       id: publish-report
       uses: nwtgck/actions-netlify@v1.2
-      #if: always() && hashFiles('acceptance/target/site/serenity/summary.txt') != ''
+      if: always() && hashFiles('acceptance/target/site/serenity/summary.txt') != ''
       with:
         publish-dir: "./acceptance/target/site/serenity/"
         production-branch: master
@@ -75,19 +76,19 @@ runs:
     - name: Read tests summary
       id: tests-summary
       uses: andstor/file-reader-action@v1
-      #if: always() && hashFiles('acceptance/target/site/serenity/summary.txt') != ''
+      if: always() && hashFiles('acceptance/target/site/serenity/summary.txt') != ''
       #continue-on-error: true
       with:
         path: "acceptance/target/site/serenity/summary.txt"
         
     - name: Send Slack notification (master only)
       uses: rtCamp/action-slack-notify@v2.2.0
-      #if: always() && github.ref == 'refs/heads/master'
+      if: always() #&& github.ref == 'refs/heads/master'
       env:
         SLACK_WEBHOOK: ${{ inputs.SLACK_WEBHOOK_QA }}
         SLACK_USERNAME: Acceptance Tests for ${{ github.event.inputs.RELEASE_CODENAME }} release
         SLACK_ICON_EMOJI: ":shipit:"
-        SLACK_COLOR: ${{env.TESTS_STATUS}}  #${{job.status}}
+        SLACK_COLOR: ${{env.TESTS_STATUS}}
         SLACK_CHANNEL:  logging-${{inputs.ENVIRONMENT_NAME}} 
         SLACK_TITLE: ${{ steps.tests-summary.outputs.contents }}
         SLACK_MESSAGE: ${{ steps.publish-report.outputs.deploy-url }}
